/** ****************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ************************************************** */

const express = require('express');
const boom = require('express-boom');
const dat = require('./api/models/test');


const app = express();
app.use(boom());
const port = process.env.PORT || 8000;

app.get('/api/imagesearch/:query', (request, response) => {
  const queryParams = (request.params.query.split('&'));
  const searchQuery = (queryParams[0]);
  const offsetValue = (parseInt(queryParams[1].split('=')[1]));

  // console.log(dat["data"][2]["url"]);


});

app.get('/api/imagesearch/history', (request, response) => {

});

app.listen(port, (err) => {
  if (err) {
    throw err;
  }
  console.log(`Image search service is running on ${port} `);
});

module.exports = app;
